### ISSUE TITLE
✨ feat: Add a StorageClass for local kubernetes clusters

### ISSUE THREAD

**Issue by PatrickLaabs** [PatrickLaabs/frigg#112]
/kind feature

**Describe the solution you'd like**
For some toolings (like Vault, or the vCluster Provider) we need a StorageClass for the local kubernetes clusters.
Check, if we can provide it easily.

**Anything else you would like to add:**
If it's possible to solve, this issue will also take care of #91

**Comment by PatrickLaabs** [comment]
https://artifacthub.io/packages/helm/containeroo/local-path-provisioner

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: standard
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

**Comment by PatrickLaabs** [comment]
```
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
    name: local-path-provisioner
spec:
    clusterSelector:
        matchLabels:
            local-path-provisioner-enabled: default
    repoURL: https://charts.containeroo.ch
    chartName: containeroo
    namespace: default
    releaseName: local-path-provisioner
    version: 0.0.26
    options:
        waitForJobs: true
        wait: true
        timeout: 5m
        install:
            createNamespace: false
    valuesTemplate: |-
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /var/local-path-provisioner
        helperImage:
          repository: docker.io/kindest/local-path-helper
          tag: v20230510-486859a6
        storageClass:
          create: true
          provisionerName: rancher.io/local-path
          defaultClass: true
```
